#!/bin/sh

#####################################################
# ctime /TR 2019-01-28
# mtime /TR 2019-01-29
#
# Helperscript for changing entries of /etc/hosts
#####################################################

HOSTFILE=/etc/hosts

case "$1" in
  add)
    $0 del $3
    echo "$2 $3" >> $HOSTFILE
    ;;
  del)
    test -z $2 && exit 111
    sed -i "/\s$2\$/d" $HOSTFILE
    ;;
  *)
    echo "usage: $0 add 1.2.3.4 example.net"
    echo "usage: $0 del example.net"
  ;;
esac
