#!/bin/sh

#####################################################
# ctime /TR 2019-01-28
# mtime /TR 2019-01-29
#
# Search IP's for YouTube servers
#####################################################

for domain in \
  m.youtube.com \
  www.youtube.com \
  youtube.googleapis.com \
  youtubei.googleapis.com \
  www.youtube-nocookie.com
do
  ip=`host -t a $domain`
  test $? != 0 && continue
  ip=`echo $ip | grep address | head -1 | sed -e 's/.* has address //g'`
  # echo "ip=$ip dom=$domain"
  ./chghosts add $ip $domain
done
